[0m11:56:31.449370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026622BB1290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026622BB2210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026622BB1E50>]}


============================== 11:56:31.451879 | 6c643257-726c-451e-bd1d-8475d74132b9 ==============================
[0m11:56:31.451879 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:56:31.451879 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Henning\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init transformation', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:56:31.460391 [info ] [MainThread]: A project called transformation already exists here.
[0m11:56:31.461407 [debug] [MainThread]: Command `dbt init` succeeded at 11:56:31.461407 after 0.05 seconds
[0m11:56:31.462397 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026622B5A090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002661CCE2F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026622B51790>]}
[0m11:56:31.462397 [debug] [MainThread]: Flushing usage events
[0m11:56:32.084380 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:58:26.295879 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69F52C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69F94290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69FB1010>]}


============================== 11:58:26.297877 | ccb62814-52e8-4e56-8baf-a91f4d2b190a ==============================
[0m11:58:26.297877 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:58:26.299385 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Henning\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init transforomation_tmp', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:58:26.313902 [debug] [MainThread]: Starter project path: C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\include\starter_project
[0m11:58:26.342458 [info ] [MainThread]: 
Your new dbt project "transforomation_tmp" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:58:26.342458 [info ] [MainThread]: Setting up your profile.
[0m11:59:57.479326 [error] [MainThread]: Encountered an error:

[0m11:59:57.482336 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Repos\Analytics-Forge-Framework\transformation\.venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:59:57.482336 [debug] [MainThread]: Command `dbt init` failed at 11:59:57.482336 after 91.23 seconds
[0m11:59:57.483337 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69F8B490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69F59FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AE69E6C2D0>]}
[0m11:59:57.483337 [debug] [MainThread]: Flushing usage events
[0m11:59:58.136771 [debug] [MainThread]: An error was encountered while trying to flush usage events
